### ISSUE TITLE
Do not compile with Carthage or SPM

### ISSUE THREAD

**Issue by mamcx** [agisboye/SwiftLMDB#15]
I create a new project with Swift 4 & XCode Version 9.2.

I try using Carthage and after the build it not show SwiftLMDB.framework anywhere. 

Then, I try to use https://swift.org/package-manager/, it get fetched ok but get:
```

/.build/checkouts/SwiftLMDB.git-2506504943730548242/Sources/DataConvertible.swift:243:33: 'dataRepresentation' is only available on OS X 10.11 or newer
/.build/checkouts/SwiftLMDB.git-2506504943730548242/Sources/DataConvertible.swift:236:25: 'init(dataRepresentation:relativeTo:isAbsolute:)' is only available on OS X 10.11 or newer
```

The deployment target is set to OS X 10.11 and  Base SDK is 10.13

**Comment by agisboye** [comment]
Hi!

This package has never been tested with Carthage. You are welcome to create the necessary changes (if any) and submit a pull request. Otherwise you will need to use Swift Package Manager.

I would bump up the deployment target but it appears that there is no way of doing so in the `Package.swift` file. Introducing xcconfigs seems messy. Instead, I've removed the offending code. If you are running macOS 10.11 or later, you can add the URL conformance to `DataConvertible` yourself in an extension. Try building the latest tag.
