### ISSUE TITLE
Cursor operations?

### ISSUE THREAD

**Issue by mikemee** [agisboye/SwiftLMDB#18]
@agisboye A great library, thanks!

Have you given any thought to adding cursor operations?  E.g. to allow iteration of the database, or for setting and fetching keys in ranges?

**Comment by agisboye** [comment]
I have! I was thinking something along the lines of making `Database` conform to the `Sequence` protocol. The iterator would be something that wraps the LMDB cursor.

If you wan't to give it a go I'm happy to take pull requests. Otherwise, I might have time to play around with it sometime next week.

[Sequence](https://developer.apple.com/documentation/swift/sequence)

**Comment by mikemee** [comment]
Thanks @agisboye !  FWIW I found these related Go libraries to be interesting for their api approaches. 

A wrapper: https://github.com/bmatsuo/lmdb-go/blob/master/README.md

A rewrite in Go https://pkg.go.dev/github.com/boltdb/bolt (or its newer maintained fork: https://github.com/etcd-io/bbolt). 

This layer on top of it has some interesting ideas: https://github.com/timshannon/bolthold

I’m trying to find something I can use in both a modern iOS and Android app. Unfortunately it seems the Android LMDB is stalled due to JNI problems, so even if you added cursors I might still end up at SQLite as the intersection of iOS & Android solutions even though it’s overkill for my scenario.

**Comment by agisboye** [comment]
Cursors for read operations have been implemented since 2.1.0.
