### ISSUE TITLE
fails to build for Swift 3.1 Package Manager project

### ISSUE THREAD

**Issue by placrosse** [agisboye/SwiftLMDB#2]

**Comment by agisboye** [comment]
I'll have a look at it. 👍🏼

**Comment by eriktier** [comment]
I've fixed this in my fork.

**Comment by agisboye** [comment]
I'm happy to merge in your fix, if you shoot me a PR.

**Comment by eriktier** [comment]
There is one issue. I got another issue report on my side that CLMDB doesn’t work on a real iOS device (only simulator). So that one needs to be fixed. I found another issue myself on the Linux side. On Linux the tests don’t run as they depend on MacOS/iOS specific features of Foundation.

I’ll make the PR.

Cheers,
   Erik

**Comment by agisboye** [comment]
Fixed with #3.
