### ISSUE TITLE
Crashes on some iOS physical devices

### ISSUE THREAD

**Issue by placrosse** [agisboye/SwiftLMDB#4]
Receive a SIGSYS when run on a real iPod Touch and iPad Mini 2.
Works OK on simulator.
Issue seems to be this: http://www.openldap.org/lists/openldap-technical/201502/msg00038.html
Fix is to Define MDB_USE_POSIX_SEM to avoid build defaulting to MDB_USE_SYSV_SEM (see within mdb.c source file).

Issue also reported to CLMDB project.  Not certain where the fix should ultimately be applied.

**Comment by agisboye** [comment]
Can you try it with the latest version of SwiftLMDB?
I've restructured the CLMDB wrapper, so that it [defines](https://github.com/agisboye/CLMDB/blob/abfc9fa9e2d048dfa52e162cf0535f7ef3494b20/Sources/include/clmdb.h#L4) `MDB_USE_POSIX_SEM`. While I like where the fix has been applied, I'm not sure it should apply to all platforms. Is this issue related to iOS only?

**Comment by placrosse** [comment]
You are correct.  It is an iOS issue, when run on real (ARM) hardware.  Running the iOS app on the Simulator on a Mac worked fine (but, this was actually a different compilation).
I suspect that the author of LMDB changed it (as the POSIX_SEM was an older option) to something which had some benefits on other platforms.
I'll try this new version on Linux and see what happens (does it at least run with a crash)?

**Comment by agisboye** [comment]
Let me know how it goes. I'm curious to hear if the library works on iOS now that LMDB is being compiled with `MDB_USE_POSIX_SEM`. Ideally we should define this only on iOS.

**Comment by mikemee** [comment]
As I consider adopting this as the core of some puzzle apps (using read-only assets like #16) and read-write for puzzle & purchase states, I wonder if this issue is still active?

I guess few will see this, but I wonder if many others are using LMDB via this wrapper on iOS?  (Also is the data format on disk likely to change in the future?)

_Looks like a great little project!_

**Comment by agisboye** [comment]
This shouldn't be an issue anymore. I think I've forgotten to close it but let me check and get back to you just to be sure.

I don't have any usage statistics, unfortunately. I originally built the wrapper for a project but ended up not needing a key/value store. I have another project in which I might use it at some point in the future.

The data format for LMDB itself is unlikely to change, I think. I can't really speak to this.
I don't see any reason to change the way we serialize types in Swift so that shouldn't be a concern either.

**Comment by mikemee** [comment]
> I don't see any reason to change the way we serialize types in Swift so that shouldn't be a concern either.

Thanks. Yes that’s the part I was concerned about.

**Comment by esummers** [comment]
> As I consider adopting this as the core of some puzzle apps (using read-only assets like #16) and read-write for puzzle & purchase states, I wonder if this issue is still active?
> 
> I guess few will see this, but I wonder if many others are using LMDB via this wrapper on iOS? (Also is the data format on disk likely to change in the future?)
> 
> _Looks like a great little project!_

It can work for small datasets, but one concern you might have is the mmap limit on iOS.  Each app is only allowed to mmap up to 700MB and some of that may be consumed by other parts of your app.  In real life plan on no more then 300MB and make sure compaction is run often enough to stay in this limit.  Since LMDB doesn’t have a fallback to paging, it might not be the best option on iOS.  LMDB was really designed for desktop and server.  If you are looking for something similar, the SQLite project has a key value database side project called LSM1.  It can be used with or independently from SQLite.  The nice thing about LSM1 is it can use mmap until it hits a certain threshold then switches to paging.  It is designed to have a low memory footprint and is excellent for mobile.
